theme = "doom_acario_dark"

[editor]
color-modes = true
cursorline = true
scrolloff = 100
indent-guides.render = true
auto-format = false
soft-wrap.enable = true
[editor.cursor-shape]
insert = "bar"
[keys.insert]
A-q = "normal_mode"
[editor.lsp]
display-messages = true
display-signature-help-docs = false
