version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.jbbjhome.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.jbbjhome.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 50080:80
      - 50443:443
      - 50022:22
    volumes:
      - gconfig:/etc/gitlab
      - glogs:/var/log/gitlab
      - gdata:/var/opt/gitlab
    shm_size: 256m
    networks:
      - devenv
  youtrack:
    image: jetbrains/youtrack:2023.1.17170
    restart: always
    hostname: youtrack.jbbjhome.com
    ports:
      - 58080:8080
    volumes:
      - yconf:/opt/youtrack/conf
      - ylogs:/opt/youtrack/logs
      - ybackups:/opt/youtrack/backups
      - ydata:/opt/youtrack/data
    networks:
      - devenv
    
volumes:
  gconfig:
  glogs:
  gdata:
  yconf:
  ylogs:
  ybackups:
  ydata:
networks:
    devenv: